package com.theorev.model;
// Generated 10/12/2017 10:23:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Controls generated by hbm2java
 */
@Entity
@Table(name = "controls", schema = "public")
public class Controls implements java.io.Serializable {

	private int id;
	private Treatments treatments;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Date fecha;
	private int pieces;
	private String description;
	private BigDecimal pago;

	public Controls() {
	}

	public Controls(int id, Treatments treatments, Date fecha, int pieces) {
		this.id = id;
		this.treatments = treatments;
		this.fecha = fecha;
		this.pieces = pieces;
	}

	public Controls(int id, Treatments treatments, Date createdAt, Date updatedAt, Date deletedAt, Date fecha,
			int pieces, String description, BigDecimal pago) {
		this.id = id;
		this.treatments = treatments;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.fecha = fecha;
		this.pieces = pieces;
		this.description = description;
		this.pago = pago;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "treatment_id", nullable = false)
	public Treatments getTreatments() {
		return this.treatments;
	}

	public void setTreatments(Treatments treatments) {
		this.treatments = treatments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 35)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 35)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 35)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "pieces", nullable = false)
	public int getPieces() {
		return this.pieces;
	}

	public void setPieces(int pieces) {
		this.pieces = pieces;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "pago", precision = 36)
	public BigDecimal getPago() {
		return this.pago;
	}

	public void setPago(BigDecimal pago) {
		this.pago = pago;
	}

}
