package com.theorev.model;
// Generated 10/12/2017 10:23:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Treatments generated by hbm2java
 */
@Entity
@Table(name = "treatments", schema = "public")
public class Treatments implements java.io.Serializable {

	private int id;
	private TreatmentDetails treatmentDetails;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private int patientId;
	private Set<Patients> patientses = new HashSet<Patients>(0);
	private Set<Controls> controlses = new HashSet<Controls>(0);

	public Treatments() {
	}

	public Treatments(int id, int patientId) {
		this.id = id;
		this.patientId = patientId;
	}

	public Treatments(int id, TreatmentDetails treatmentDetails, Date createdAt, Date updatedAt, Date deletedAt,
			int patientId, Set<Patients> patientses, Set<Controls> controlses) {
		this.id = id;
		this.treatmentDetails = treatmentDetails;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.patientId = patientId;
		this.patientses = patientses;
		this.controlses = controlses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "treatment_detail_id")
	public TreatmentDetails getTreatmentDetails() {
		return this.treatmentDetails;
	}

	public void setTreatmentDetails(TreatmentDetails treatmentDetails) {
		this.treatmentDetails = treatmentDetails;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 35)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 35)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 35)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "treatments")
	public Set<Patients> getPatientses() {
		return this.patientses;
	}

	public void setPatientses(Set<Patients> patientses) {
		this.patientses = patientses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "treatments")
	public Set<Controls> getControlses() {
		return this.controlses;
	}

	public void setControlses(Set<Controls> controlses) {
		this.controlses = controlses;
	}

}
