package com.theorev.model;
// Generated 10/12/2017 10:23:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TreatmentDetails generated by hbm2java
 */
@Entity
@Table(name = "treatment_details", schema = "public")
public class TreatmentDetails implements java.io.Serializable {

	private int id;
	private Works works;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private int quantity;
	private Set<Treatments> treatmentses = new HashSet<Treatments>(0);

	public TreatmentDetails() {
	}

	public TreatmentDetails(int id, int quantity) {
		this.id = id;
		this.quantity = quantity;
	}

	public TreatmentDetails(int id, Works works, Date createdAt, Date updatedAt, Date deletedAt, int quantity,
			Set<Treatments> treatmentses) {
		this.id = id;
		this.works = works;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.quantity = quantity;
		this.treatmentses = treatmentses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "work_id")
	public Works getWorks() {
		return this.works;
	}

	public void setWorks(Works works) {
		this.works = works;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 35)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 35)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 35)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "treatmentDetails")
	public Set<Treatments> getTreatmentses() {
		return this.treatmentses;
	}

	public void setTreatmentses(Set<Treatments> treatmentses) {
		this.treatmentses = treatmentses;
	}

}
